### ISSUE TITLE
variable undefined error

### ISSUE THREAD

**Issue by byteshiva** [pgolm/ansible-role-monit#37]
can you let me know why its throwing variable undefined!!

`the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode' object has no attribute 'name'\n\nThe error appears to have been in '/root/ansible-consul-temp/roles/pgolm.monit/tasks/monitors.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: monitors - Write monitors\n  ^ here\n`

**Comment by meznom** [comment]
I ran into the same issue. It's fixed for my by pull request #40.

**Comment by pgolm** [comment]
This should be fixed on master. Thx to @vkill
